# Generated by Django 5.0.2 on 2024-02-12 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=150)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('age', models.IntegerField(default=18)),
                ('description', models.TextField(max_length=100)),
                ('model_name', models.CharField(max_length=40)),
                ('rating', models.FloatField(default=1)),
                ('ig_followers', models.IntegerField(default=0)),
                ('yt_subscribers', models.IntegerField(default=0)),
                ('x_followers', models.IntegerField(default=0)),
                ('tiktok_followers', models.IntegerField(default=0)),
                ('fb_followers', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Celeb_occupations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celeb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.celeb')),
                ('occupation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.occupations')),
            ],
        ),
    ]
