# Generated by Django 5.0.2 on 2024-02-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Celeb_occupations',
            new_name='Celeb_occupation',
        ),
        migrations.RenameModel(
            old_name='Occupations',
            new_name='Occupation',
        ),
    ]
