# Generated by Django 5.0.2 on 2024-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_rename_celeb_occupations_celeb_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeb',
            name='profile_image',
            field=models.ImageField(default='static/img/png/default.png', upload_to='profile_pics'),
        ),
    ]
