# Generated by Django 5.0.2 on 2024-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_celeb_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeb',
            name='profile_image',
            field=models.ImageField(default='static/img/png/default.png', upload_to='static/img/celeb_pics'),
        ),
    ]
